#!/usr/bin/env bash

NVM_VERSION="v0.33.6"
LUMO_VERSION="1.9.0-alpha"

pacman -Syu --noconfirm
pacman -S --noconfirm git npm python2 make gcc bc awk
pacman -Scc --noconfirm
ln -s /usr/sbin/python2 /usr/sbin/python
ln -s /usr/sbin/python2-config /usr/sbin/python-config
npm install -g lumo-cljs@$LUMO_VERSION --unsafe-perm
curl "https://raw.githubusercontent.com/creationix/nvm/${NVM_VERSION}/install.sh" | bash
. "$HOME/.nvm/nvm.sh" && nvm install $(lumo -e '(println process.version)') && npm install
