#!/usr/bin/env bash

NVM_VERSION="v0.33.6"

brew upgrade node
HOMEBREW_NO_AUTO_UPDATE=1 brew install wget bc
npm install -g lumo-cljs --unsafe-perm
wget -qO- "https://raw.githubusercontent.com/creationix/nvm/${NVM_VERSION}/install.sh" | bash
. "$HOME/.nvm/nvm.sh" && nvm install $(lumo -e '(println process.version)') && npm install
